steps:
  - name: 'docker:29'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/reload/image:latest',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/reload/image:$COMMIT_SHA',
        '--build-arg',
        'BUILDKIT_INLINE_CACHE=1',
        '--cache-from',
        'us-central1-docker.pkg.dev/$PROJECT_ID/reload/image:latest',
        '.',
      ]
    env: [DOCKER_BUILDKIT=1]

  - name: 'docker:29'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only push "latest" tag when building on "main"
        [ "$BRANCH_NAME" != "main" ] && exit 0
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/reload/image:latest

images: [
  'us-central1-docker.pkg.dev/$PROJECT_ID/reload/image:$COMMIT_SHA',
]
