name: ci
on:
  push:
    branches:
      - master
      - releases/**
  pull_request:

jobs:
  test:
    name: lint and test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      # Until GH composite actions can use `uses`, we need to setup python here
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - run: make requirements-test

      - run: make lint

      - run: make test
