name: ci
on:
  push:
    branches:
      - master
      - releases/**
  pull_request:

jobs:
  test:
    name: lint and test
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Until GH composite actions can use `uses`, we need to setup python here
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pytest-cov

      - run: make requirements-test

      - run: make lint

      - run: make test

      - run: |
          pytest --cov=./ --cov-report=xml
          bash <(curl https://codecov.io/bash)
